# Mosquitto Broker — Quadra Inteligente de Beach Tennis
# Porta padrão MQTT (TCP)
listener 1883
allow_anonymous true

# Porta WebSocket (necessário para o Wokwi conectar via Gateway)
listener 9001
protocol websockets
allow_anonymous true
